@startuml
    left to right direction
    actor Osbert
    actor Cliente
    rectangle Compra{
        Cliente -- (Compra)
        (Vender) -- Osbert
        (Reportes) -- Osbert
        Cliente -- (Reportes)
    }
@enduml
